package com.rsbuddy.script.wrappers;

public enum BankEvent {

	DEPOSIT_ALL,
	DEPOSIT_ALL_EXCEPT,
	DEPOSIT,
	WITHDRAW,
	WITHDRAW_IF_INVENTORY_DOESNT_CONTAIN,
	WITHDRAW_NOTED,
	WITHDRAW_NOTED_IF_INVENTORY_DOESNT_CONTAIN;
}